# Base configs
#baseurl: "https://vexetron.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
#google_analytics: "UA-46465113-2"

# UI configs
title: "vexetron"
#subtitle: ""
author: "vexetron"
header:
 title: "Photos"
 subtitle: "by vexetron"
footer:
 name: "Hi there!"
 #bio: ""
 #github: ""
web_design: "AJ"
social_urls:
  twitter: "https://www.twitter.com/vexetron"
  instagram: "https://www.instagram.com/nortexev"
  #dribbble: "https://dribbble.com/rampatra"
  #linkedin: "https://in.linkedin.com/in/ram-patra"
  github: "https://www.github.com/vexetron"
